# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oIos6-K51PhXoBo575Af2wxFS7V17ns2
"""



# Commented out IPython magic to ensure Python compatibility.
# import streamlit as st
# import datetime
# import pandas as pd
# import os
# import plotly.express as px  # <-- เพิ่มไลบรารีสำหรับทำกราฟ
# 
# st.set_page_config(page_title="ระบบจัดการรายรับ-รายจ่าย", page_icon="💰", layout="wide")
# 
# # ================= ระบบจัดการฐานข้อมูล (ไฟล์ CSV) =================
# DATA_FILE = "expense_data.csv"
# 
# def load_data():
#     if os.path.exists(DATA_FILE):
#         try:
#             df = pd.read_csv(DATA_FILE)
#             records = {}
#             for _, row in df.iterrows():
#                 date_obj = datetime.datetime.strptime(str(row['Date']), '%Y-%m-%d').date()
#                 records[int(row['ID'])] = {
#                     'Date': date_obj,
#                     'Type': row['Type'],
#                     'Description': row['Description'],
#                     'Amount': float(row['Amount'])
#                 }
#             next_id = int(df['ID'].max()) + 1 if not df.empty else 1
#             return records, next_id
#         except Exception as e:
#             st.error(f"เกิดข้อผิดพลาดในการโหลดไฟล์: {e}")
#             return {}, 1
#     return {}, 1
# 
# def save_data(records):
#     if not records:
#         df = pd.DataFrame(columns=['ID', 'Date', 'Type', 'Description', 'Amount'])
#         df.to_csv(DATA_FILE, index=False)
#         return
# 
#     data_list = []
#     for r_id, r_data in records.items():
#         data_list.append({
#             'ID': r_id,
#             'Date': r_data['Date'].strftime('%Y-%m-%d'),
#             'Type': r_data['Type'],
#             'Description': r_data['Description'],
#             'Amount': r_data['Amount']
#         })
#     df = pd.DataFrame(data_list)
#     df.to_csv(DATA_FILE, index=False)
# 
# # ================= ดึงข้อมูลเมื่อเริ่มโปรแกรม =================
# if 'records' not in st.session_state:
#     st.session_state.records, st.session_state.next_id = load_data()
# 
# def get_dataframe(records_dict):
#     if not records_dict:
#         return pd.DataFrame()
#     df = pd.DataFrame.from_dict(records_dict, orient='index')
#     df.index.name = 'ID'
#     df.reset_index(inplace=True)
#     df = df.sort_values(by='Date')
#     return df
# 
# st.title("📑 ระบบบริหารจัดการรายรับ-รายจ่าย")
# 
# tab1, tab2, tab3, tab4, tab5 = st.tabs([
#     "➕ เพิ่มรายการ",
#     "📊 แสดงข้อมูลและสรุปยอด",
#     "🔍 ค้นหาข้อมูล",
#     "✏️ แก้ไขข้อมูล",
#     "🗑️ ลบข้อมูล"
# ])
# 
# # --- แท็บ 1: เพิ่มรายการ ---
# with tab1:
#     st.header("เพิ่มรายการใหม่")
#     with st.form("add_form"):
#         col1, col2 = st.columns(2)
#         with col1:
#             date_input = st.date_input("วันที่", datetime.date.today())
#             type_input = st.selectbox("ประเภท", ["รายรับ", "รายจ่าย"])
#         with col2:
#             desc_input = st.text_input("รายละเอียดรายการ")
#             amount_input = st.number_input("จำนวนเงิน (บาท)", min_value=0.0, step=10.0)
# 
#         submitted = st.form_submit_button("บันทึกข้อมูล")
# 
#         if submitted:
#             if desc_input == "":
#                 st.error("กรุณากรอกรายละเอียดรายการ!")
#             elif amount_input <= 0:
#                 st.error("กรุณากรอกจำนวนเงินให้ถูกต้อง!")
#             else:
#                 st.session_state.records[st.session_state.next_id] = {
#                     'Date': date_input,
#                     'Type': type_input,
#                     'Description': desc_input,
#                     'Amount': amount_input
#                 }
#                 save_data(st.session_state.records)
#                 st.success(f"✅ เพิ่มข้อมูลสำเร็จ! (ID: {st.session_state.next_id})")
#                 st.session_state.next_id += 1
# 
# # --- แท็บ 2: แสดงข้อมูลและสรุปยอด (อัปเดตเพิ่มกราฟ) ---
# with tab2:
#     st.header("ข้อมูลทั้งหมดและสรุปยอด")
#     if not st.session_state.records:
#         st.info("📭 ยังไม่มีข้อมูลในระบบ")
#     else:
#         total_income = sum(r['Amount'] for r in st.session_state.records.values() if r['Type'] == 'รายรับ')
#         total_expense = sum(r['Amount'] for r in st.session_state.records.values() if r['Type'] == 'รายจ่าย')
#         balance = total_income - total_expense
# 
#         # กล่องตัวเลขสรุปยอด
#         col1, col2, col3 = st.columns(3)
#         col1.metric("🟢 รายรับรวม", f"{total_income:,.2f} บาท")
#         col2.metric("🔴 รายจ่ายรวม", f"{total_expense:,.2f} บาท")
#         col3.metric("🔵 ยอดคงเหลือ", f"{balance:,.2f} บาท")
# 
#         st.markdown("---")
# 
#         # แบ่งหน้าจอเป็น 2 ฝั่ง (ซ้ายดูกราฟ ขวาดูตาราง)
#         col_chart, col_table = st.columns([1, 1.2])
# 
#         with col_chart:
#             st.subheader("📊 สัดส่วนรายจ่าย")
#             expense_data = [r for r in st.session_state.records.values() if r['Type'] == 'รายจ่าย']
#             if expense_data:
#                 df_exp = pd.DataFrame(expense_data)
#                 df_grouped = df_exp.groupby('Description', as_index=False)['Amount'].sum()
# 
#                 fig = px.pie(
#                     df_grouped,
#                     values='Amount',
#                     names='Description',
#                     hole=0.4,
#                     color_discrete_sequence=px.colors.sequential.RdBu
#                 )
#                 fig.update_traces(textposition='inside', textinfo='percent+label')
#                 fig.update_layout(showlegend=False, margin=dict(t=0, b=0, l=0, r=0))
# 
#                 st.plotly_chart(fig, use_container_width=True)
#             else:
#                 st.info("ยังไม่มีข้อมูลรายจ่ายสำหรับสร้างกราฟ")
# 
#         with col_table:
#             st.subheader("📑 ตารางรายการล่าสุด")
#             df = get_dataframe(st.session_state.records)
#             st.dataframe(df, use_container_width=True, hide_index=True)
# 
#             # --- ส่วนที่เพิ่มเข้ามา: ปุ่มดาวน์โหลดไฟล์ CSV ---
#             st.markdown("<br>", unsafe_allow_html=True) # เว้นบรรทัดนิดนึง
#             csv = df.to_csv(index=False).encode('utf-8')
#             st.download_button(
#                 label="📥 ดาวน์โหลดข้อมูลเป็นไฟล์ Excel (CSV)",
#                 data=csv,
#                 file_name='my_expenses.csv',
#                 mime='text/csv',
#                 type="primary"
#             )
# 
# # --- แท็บ 3: ค้นหาข้อมูล ---
# with tab3:
#     st.header("ค้นหาข้อมูล")
#     search_term = st.text_input("ค้นหาจากวันที่ (เช่น 2026-03) หรือคำอธิบายรายการ:")
#     if search_term:
#         results = {
#             k: v for k, v in st.session_state.records.items()
#             if search_term in str(v['Date']) or search_term.lower() in v['Description'].lower()
#         }
#         if results:
#             st.success(f"🔎 พบข้อมูล {len(results)} รายการ")
#             df = get_dataframe(results)
#             st.dataframe(df, use_container_width=True, hide_index=True)
#         else:
#             st.warning("ไม่พบข้อมูลที่ค้นหา")
# 
# # --- แท็บ 4: แก้ไขข้อมูล ---
# with tab4:
#     st.header("แก้ไขข้อมูล")
#     if not st.session_state.records:
#         st.info("📭 ยังไม่มีข้อมูลให้แก้ไข")
#     else:
#         df = get_dataframe(st.session_state.records)
#         st.dataframe(df, use_container_width=True, hide_index=True)
#         record_id = st.number_input("กรอก ID ที่ต้องการแก้ไข", min_value=1, step=1)
# 
#         if record_id in st.session_state.records:
#             current_data = st.session_state.records[record_id]
#             st.markdown(f"**กำลังแก้ไข ID:** {record_id}")
#             with st.form("edit_form"):
#                 new_date = st.date_input("วันที่", current_data['Date'])
#                 type_index = 0 if current_data['Type'] == 'รายรับ' else 1
#                 new_type = st.selectbox("ประเภท", ["รายรับ", "รายจ่าย"], index=type_index)
#                 new_desc = st.text_input("รายละเอียดรายการ", current_data['Description'])
#                 new_amount = st.number_input("จำนวนเงิน (บาท)", min_value=0.0, value=float(current_data['Amount']), step=10.0)
#                 submitted = st.form_submit_button("อัปเดตข้อมูล")
#                 if submitted:
#                     st.session_state.records[record_id] = {'Date': new_date, 'Type': new_type, 'Description': new_desc, 'Amount': new_amount}
#                     save_data(st.session_state.records)
#                     st.success("✅ อัปเดตข้อมูลเรียบร้อยแล้ว!")
#         else:
#             if record_id > 0:
#                 st.error(f"❌ ไม่พบ ID {record_id} ในระบบ")
# 
# # --- แท็บ 5: ลบข้อมูล ---
# with tab5:
#     st.header("ลบข้อมูล")
#     if not st.session_state.records:
#         st.info("📭 ยังไม่มีข้อมูลให้ลบ")
#     else:
#         df = get_dataframe(st.session_state.records)
#         st.dataframe(df, use_container_width=True, hide_index=True)
#         record_id = st.number_input("กรอก ID ที่ต้องการลบ", min_value=1, step=1)
# 
#         if st.button("ยืนยันการลบ", type="primary"):
#             if record_id in st.session_state.records:
#                 del st.session_state.records[record_id]
#                 new_records = {}
#                 new_id = 1
#                 for old_id in sorted(st.session_state.records.keys()):
#                     new_records[new_id] = st.session_state.records[old_id]
#                     new_id += 1
#                 st.session_state.records = new_records
#                 st.session_state.next_id = new_id
#                 save_data(st.session_state.records)
#                 st.success(f"✅ ลบข้อมูลและจัดเรียง ID ใหม่เรียบร้อยแล้ว!")
#                 st.rerun()
#             else:
#                 st.error(f"❌ ไม่พบ ID {record_id} ในระบบ")

